language: php
php:
  - 8.0
  - 8.1
  - 8.2
  - 8.3
sudo: false
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  include:
    - php: 8.0
      env: dependencies=lowest
    - php: 8.1
      env: dependencies=lowest
    - php: 8.2
      env: dependencies=lowest
    - php: 8.3
      env: dependencies=lowest
before_script:
  - composer self-update
  - if [ -z "$dependencies" ]; then composer install; fi;
  - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest; fi;
script:
 - if [ "$TRAVIS_PHP_VERSION" != "7.1" ]; then vendor/bin/phpunit; fi
 - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover; fi
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
